version: '3.6'
services:
  redis:
    container_name: "redis_cookie_2"
    image: redis:6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - ./redis:/var/lib/redis